language: php

dist: trusty

env:
  global:
    - COMPOSER_ROOT_VERSION="3.x-dev"

matrix:
  include:
    - php: 7.1
      env: DB=MYSQL INSTALLER_VERSION=4.2.x-dev PHPCS_TEST=1 PHPUNIT_TEST=1
    - php: 7.1
      env: DB=PGSQL INSTALLER_VERSION=4.3.x-dev PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL INSTALLER_VERSION=4.4.x-dev PHPUNIT_COVERAGE_TEST=1
    - php: 7.3
      env: DB=MYSQL INSTALLER_VERSION=4.5.x-dev PHPUNIT_TEST=1 SUBSITES=1
    - php: 7.4
      env: DB=MYSQL INSTALLER_VERSION=4.6.x-dev PHPUNIT_TEST=1

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit=2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  - composer validate
  - composer require symbiote/silverstripe-queuedjobs:^4 --no-update
  - if [[ $SUBSITES ]]; then composer require silverstripe/subsites:^2 --no-update; fi
  - if [[ $DB == "PGSQL" ]]; then composer require silverstripe/postgresql:^2 --no-update; fi
  - composer require --no-update sminnee/phpunit-mock-objects:^3
  - composer require silverstripe/installer "$INSTALLER_VERSION" --no-update
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src tests; fi

after_success:
  - if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi
